# Generated by Django 3.1.4 on 2020-12-07 16:38

import accounts.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Of_Birth', models.DateField(null=True)),
                ('Phone_number', models.CharField(max_length=10, null=True, unique=True)),
                ('Age', models.CharField(max_length=3, null=True)),
                ('Guard', models.CharField(max_length=40, null=True)),
                ('Course', models.CharField(max_length=40, null=True)),
                ('Aadhar', models.CharField(max_length=12, null=True)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=None, max_length=50, null=True)),
                ('Permanent_Address', models.TextField(null=True)),
                ('Per_Taluk', models.CharField(max_length=30, null=True)),
                ('Per_Pin_Code', models.CharField(max_length=6, null=True)),
                ('Per_State', models.CharField(max_length=30, null=True)),
                ('Per_Dist', models.CharField(max_length=30, null=True)),
                ('Address', models.TextField(null=True)),
                ('Dist', models.CharField(max_length=30, null=True)),
                ('Taluk', models.CharField(max_length=30, null=True)),
                ('Pin_Code', models.CharField(max_length=6, null=True)),
                ('State', models.CharField(max_length=30, null=True)),
                ('Image', models.ImageField(null=True, upload_to='profiles', validators=[accounts.validators.validProfile], verbose_name='')),
                ('Sign', models.ImageField(null=True, upload_to='Signs', validators=[accounts.validators.validSign], verbose_name='')),
                ('Department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.departments')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
