# Generated by Django 3.1.4 on 2020-12-07 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='departments',
            fields=[
                ('name', models.CharField(blank=True, default=None, max_length=30, primary_key=True, serialize=False)),
                ('img', models.ImageField(null=True, upload_to='Departments')),
                ('desc', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='universityExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('code', models.CharField(max_length=30, null=True)),
                ('practical', models.BooleanField(blank=True, default=False)),
                ('price', models.IntegerField(default=None, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Semester', models.CharField(choices=[('SEMESTER I', 'SEMESTER I'), ('SEMESTER II', 'SEMESTER II'), ('SEMESTER III', 'SEMESTER III'), ('SEMESTER IV', 'SEMESTER IV'), ('SEMESTER V', 'SEMESTER V'), ('SEMESTER VI', 'SEMESTER VI')], default=None, max_length=40, null=True)),
                ('Subject_name', models.CharField(max_length=50, null=True)),
                ('Subject_code', models.CharField(max_length=50, null=True)),
                ('Department_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.departments')),
            ],
        ),
        migrations.CreateModel(
            name='revaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('code', models.CharField(max_length=30, null=True)),
                ('marks', models.CharField(max_length=30, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='department_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('About', models.TextField(null=True)),
                ('name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.departments')),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_type', models.CharField(choices=[('UG', 'UG'), ('PG', 'PG'), ('M.Phil', 'M.Phil'), ('Ph.D', 'Ph.D')], default=None, max_length=40, null=True)),
                ('Course_name', models.CharField(max_length=80, null=True)),
                ('Course_duration', models.CharField(max_length=30, null=True)),
                ('Department_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.departments')),
            ],
        ),
        migrations.CreateModel(
            name='carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(null=True, upload_to='Carousel')),
                ('Img_title', models.CharField(max_length=30, null=True)),
                ('Img_desc', models.CharField(max_length=500, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.departments')),
            ],
        ),
    ]
